# Generated by Django 3.2 on 2021-04-24 13:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20210424_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='Isbn',
            new_name='isbn',
        ),
        migrations.AlterField(
            model_name='isbn',
            name='author_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='book_title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='isbn_number',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='store',
            name='thumb',
            field=models.ImageField(blank=True, null=True, upload_to='books'),
        ),
    ]
